# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oWz9sbVg2W5SwEKGTC8GcVw_3-zQJgIu
"""

import gradio as gr

from transformers import pipeline

#load the pre trained sentiment analysis model
sentiment_analyzer = pipeline("sentiment-analysis")

#define the funtion that will wrao our model
def analyze_sentiment(text):
  result = sentiment_analyzer(text)[0]
  #gradio works best with dictionary outputs
  return {result['label']: result ['score']}

#create the gradio interface
iface= gr.Interface(
    fn=analyze_sentiment,
    inputs = gr.Textbox(lines=2, placeholder="Enter a sentence here.."),
    outputs="label",
    title="Sentiment Analysis Bot",
    description =' Type in a sentence and see if the model thinks its positive or negative.Built with Gradio and Hugging Face'
)
#launch the app
iface.launch(share=True)

